### ISSUE TITLE
factry week1

### ISSUE THREAD

**Issue by sushmarchandran** [sushmarchandran/factry#1]
Output from eg2:

rank ,         name ,    med   ,  iqr <br />
---------------------------------------------------- <br />
   1 ,           nb ,      45  ,    18 (   ------  *  -|---           ),27.00, 41.00, 45.00, 52.00, 64.00 <br />
   1 ,          j48 ,      47  ,    25 ( -------    *  |---           ),22.00, 38.00, 47.00, 56.00, 64.00<br />
   2 ,       rbfnet ,      56  ,    10 (         ----  * -----        ),42.00, 50.00, 56.00, 59.00, 73.00<br />
   2 ,         bnet ,      58  ,    17 (       ------  |*   ------    ),37.00, 50.00, 58.00, 67.00, 81.00<br />
pf

rank ,         name ,    med   ,  iqr <br />
----------------------------------------------------<br />
   1 ,           nb ,       8  ,     6 (    --   * ----|-             ), 4.00,  6.00,  8.00, 10.00, 15.00<br />
   2 ,       rbfnet ,       9  ,     7 (    ----- *    |-----         ), 4.00,  8.00,  9.00, 14.00, 19.00<br />
   2 ,          j48 ,      10  ,    10 (   -----   *   |  ------      ), 3.00,  7.00, 10.00, 16.00, 21.00<br />
   2 ,         bnet ,      13  ,     8 (        ---   *|   --         ), 7.00, 10.00, 13.00, 17.00, 19.00<br />

Link to report: http://tiny.cc/9rnzby

**Comment by timm** [comment]
```
rank , name , med , iqr 
---------------------------------------------------- 

1 , nb , 45 , 18 ( ------ * -|--- ),27.00, 41.00, 45.00, 52.00, 64.00 
1 , j48 , 47 , 25 ( ------- * |--- ),22.00, 38.00, 47.00, 56.00, 64.00
2 , rbfnet , 56 , 10 ( ---- * ----- ),42.00, 50.00, 56.00, 59.00, 73.00
2 , bnet , 58 , 17 ( ------ |* ------ ),37.00, 50.00, 58.00, 67.00, 81.00

pf

rank , name , med , iqr 
----------------------------------------------------

1 , nb , 8 , 6 ( -- * ----|- ), 4.00, 6.00, 8.00, 10.00, 15.00
2 , rbfnet , 9 , 7 ( ----- * |----- ), 4.00, 8.00, 9.00, 14.00, 19.00
2 , j48 , 10 , 10 ( ----- * | ------ ), 3.00, 7.00, 10.00, 16.00, 21.00
2 , bnet , 13 , 8 ( --- *| -- ), 7.00, 10.00, 13.00, 17.00, 19.00
```

**Comment by timm** [comment]
can't get to your report

![image](https://cloud.githubusercontent.com/assets/29195/15858638/82d7d766-2c8f-11e6-8dc4-377db2dca274.png)

**Comment by sushmarchandran** [comment]
@timm 
Sorry professor. Hope this works: http://tiny.cc/ng40by

**Comment by timm** [comment]
v.good. now plz do it again, with at least one reference, 

oh- and please try using acm sig alterate (double column) https://www.acm.org/publications/proceedings-template
